### PR TITLE
Fix missing namespace prefixes that occur when parsing IO in chunks

### PR DESCRIPTION
**Pull request by abargnesi**
Thanks to @sanea for the debugging. He discovered that the namespace prefixes are lost when they occur between IO chunks.

This PR addresses the issue and provides the regenerated ragel parser.

@sanea Please take a look.

### CODE REVIEW

**Comment by abargnesi** [comment]
Addressed Ruby 2.0.0 build failure in aa3918d.

**Comment by sanea** [comment]
Thanks! Everything looks great! Nothing to add.

**Comment by abargnesi** [comment]
Awesome thanks.

**Comment by abargnesi** [comment]
Rubinius 3.14 does not install properly on Travis CI, marked as allowable failure. I have confirmed with a local build of Rubinius 3.14 that `rake unit integration` passes.

**Comment by abargnesi** [comment]
The travis build succeeded for targeted jobs. Jobs that are allowed to fail are still running.

**Pull request merged**
