### PR TITLE
Migrate format extensions to translator plugins

### PR DESCRIPTION
**Pull request by abargnesi**
This pull request provides a more descriptive translation API over a simple plugin abstraction.

Highlights:

- Removed extension code in favor of the [little-plugger](https://github.com/TwP/little-plugger) gem. This gem provides a single ruby file that is vendored in the source tree at `lib/bel/vendor/little-plugger.rb`.
  - little-plugger provides plugins to be grouped by module and path (e.g. `BEL::Translator::Plugins` and `bel/translator/plugins`).
- Provide a simple `read`/`write` translator API.
- Moved plugin identifier methods to the plugin module. This cleanly separates an instance of BEL::Translator from plugin metadata.
- Translator plugins are lazily loaded when the first interaction to find a translator plugin occurs.
- Factored out JSON read/write implementations to `bel/json.rb`. The API exposed allows for streaming read/write if the implementation allows.
- Ported all five formats over to translator plugins.
  - BEL Script
  - XBEL
  - JGF
  - JSON Evidence
  - RDF

### CODE REVIEW

**Comment by abargnesi** [comment]
A follow-up issue will be to provide an execute command (e.g. something narrow like `bel list-plugins`) to make it easy to check loaded plugins.

**Comment by abargnesi** [comment]
The [travis build](https://travis-ci.org/OpenBEL/bel.rb/builds/91476421) looks good. Failures with rubinius and jruby are unrelated to this work.

**Comment by nbargnesi** [comment]
Merging; but I'd like to see some additional documentation get added. For example, what are the [read](https://github.com/abargnesi/bel.rb/commit/e010fd02d5d276e02fd53b715f81956fa7864484#diff-b272742c1a491be4ec0b0075f41019aeL76) and [write](https://github.com/abargnesi/bel.rb/commit/e010fd02d5d276e02fd53b715f81956fa7864484#diff-b272742c1a491be4ec0b0075f41019aeL80) contracts? What are the options hashes capable of holding?

**Comment by abargnesi** [comment]
Thanks for the review! I will add additional documentation.

The read/write documentation was added in the last commit ([starting at here](https://github.com/abargnesi/bel.rb/commit/c8bfc391af335c6b53b8367dfbb03a082cab85bd#diff-b272742c1a491be4ec0b0075f41019aeR48)).

The options hash are intended as pass-through configuration for the implementation. For example with an RDF translator a `:format` option could be passed to indicate the RDF format. I will be clearer on this point.

**Pull request merged**
